const $=s=>document.querySelector(s);let events=[];
const demo=`2026-09-05T09:00:03.101Z INFO api GET /v1/orders 200 request_id=req-1401
2026-09-05T09:02:18.202Z WARN payments POST /v1/checkout 429 rate limit approaching for customer 98102
2026-09-05T09:04:09.400Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781248
2026-09-05T09:05:26.002Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781249
2026-09-05T09:07:11.921Z ERROR api GET /v1/orders/781248 DatabaseError: connection pool exhausted (pool=primary-04)
2026-09-05T09:09:42.118Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781250
2026-09-05T09:12:19.110Z ERROR api GET /v1/orders/781249 DatabaseError: connection pool exhausted (pool=primary-06)
2026-09-05T09:14:02.414Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781251
2026-09-05T09:18:52.917Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781252
2026-09-05T09:20:31.619Z ERROR api GET /v1/orders/781250 DatabaseError: connection pool exhausted (pool=primary-03)
2026-09-05T09:23:08.380Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781253
2026-09-05T09:26:55.243Z ERROR worker POST /v1/refunds StripeError: charge ch_3Qze10kP failed for customer cus_P01a9
2026-09-05T09:29:06.101Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781254
2026-09-05T09:31:44.788Z ERROR api GET /v1/orders/781251 DatabaseError: connection pool exhausted (pool=primary-04)
2026-09-05T09:34:29.422Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781255
2026-09-05T09:40:16.144Z ERROR worker POST /v1/refunds StripeError: charge ch_9Abc73Pr failed for customer cus_Z20h2
2026-09-05T09:44:09.985Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781256
2026-09-05T09:48:21.067Z ERROR api GET /v1/orders/781252 DatabaseError: connection pool exhausted (pool=primary-01)
2026-09-05T09:57:31.502Z ERROR payments POST /v1/checkout PaymentProviderTimeout: gateway timed out after 30000ms for order 781257`;
function normalize(s){return s.replace(/[0-9a-f]{8}-[0-9a-f-]{27,}/gi,'<uuid>').replace(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g,'<ip>').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'<email>').replace(/\b(?:ch|cus|req)_[\w-]+\b/g,'<token>').replace(/\b(?:sk|pk)_[\w-]+\b/g,'<secret>').replace(/\b\d+\b/g,'<n>').replace(/primary-<n>/g,'primary-<n>').replace(/\b[0-9a-f]{12,}\b/gi,'<hash>')}
function parse(text){let lines=text.trim().split(/\r?\n/);if(lines[0]?.toLowerCase().includes('timestamp')&&lines[0].includes(',')){let h=lines.shift().split(',').map(x=>x.trim().toLowerCase());return lines.map(l=>{let a=l.split(',');return {time:new Date(a[h.indexOf('timestamp')]),level:(a[h.indexOf('level')]||'INFO').toUpperCase(),service:a[h.indexOf('service')]||'unknown',endpoint:a[h.indexOf('endpoint')]||'—',message:a[h.indexOf('message')]||a.at(-1),raw:l}})}return lines.map(raw=>{let time=new Date((raw.match(/\d{4}-\d\d-\d\d[T ][\d:.+-]+Z?/)||[])[0]||Date.now());let level=(raw.match(/\b(ERROR|WARN(?:ING)?|INFO|DEBUG|FATAL)\b/i)||[, 'INFO'])[1].toUpperCase().replace('WARNING','WARN');let endpoint=(raw.match(/\b(?:GET|POST|PUT|PATCH|DELETE)\s+(\/[^\s?]+)/)||[, '—','—'])[2];let after=raw.replace(/^.*?\b(?:ERROR|WARN(?:ING)?|INFO|DEBUG|FATAL)\b\s*/i,'');let service=(after.match(/^[\w.-]+/)||['unknown'])[0];let message=after.replace(/^[\w.-]+\s+(?:(?:GET|POST|PUT|PATCH|DELETE)\s+\/\S+\s*)?/,'').replace(/^\d{3}\s+/,'')||raw;return{time,level,service,endpoint,message,raw}})}
function groups(){let m=new Map;events.filter(e=>e.level==='ERROR'||e.level==='FATAL').forEach(e=>{let k=normalize(e.message);if(!m.has(k))m.set(k,{sig:k,items:[]});m.get(k).items.push(e)});return[...m.values()].sort((a,b)=>b.items.length-a.items.length)}
function fmtTime(d){return isNaN(d)?'unknown':d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}function analyze(name,text){events=parse(text);$('#fileName').textContent=name;$('#fileMeta').textContent=`${events.length} events · ${events.filter(e=>!isNaN(e.time)).length} timestamped · parsed locally`;$('#analysis').hidden=false;$('#aiPanel').hidden=false;$('#aiOutput').hidden=true;$('#aiStatus').textContent='No raw log lines are sent.';$('#aiBtn').disabled=false;$('#aiBtn').textContent='Generate AI analysis';render();$('#analysis').scrollIntoView({behavior:'smooth',block:'start'})}
function render(){let es=events.filter(e=>e.level==='ERROR'||e.level==='FATAL'), warns=events.filter(e=>e.level==='WARN'), gs=groups(), valid=events.filter(e=>!isNaN(e.time)).sort((a,b)=>a.time-b.time);let start=valid[0]?.time,end=valid.at(-1)?.time;$('#stats').innerHTML=`<div class="stat"><strong class="up">${es.length}</strong><small>ERROR EVENTS</small></div><div class="stat"><strong>${warns.length}</strong><small>WARNINGS</small></div><div class="stat"><strong>${gs.length}</strong><small>FAILURE SIGNATURES</small></div><div class="stat"><strong>${start?Math.max(1,Math.round((end-start)/60000))+'m':'—'}</strong><small>INCIDENT WINDOW</small></div>`;$('#groupCount').textContent=`${gs.length} groups`;renderChart(es,valid);$('#groupList').innerHTML=gs.map((g,i)=>`<article class="group"><div class="rank">0${i+1}</div><div><p class="signature">${esc(g.sig)}</p><p class="sample">Sample: ${esc(g.items[0].raw)}</p></div><div class="count">${g.items.length}<small>occurrences</small></div></article>`).join('')||'<p class="muted">No ERROR or FATAL events found.</p>';let impacts=new Map;es.forEach(e=>{let k=e.endpoint==='—'?e.service:e.endpoint;impacts.set(k,(impacts.get(k)||0)+1)});$('#impactList').innerHTML=[...impacts].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,n])=>`<div class="impact-item"><div class="impact-icon">↗</div><div><b>${esc(k)}</b><small>affected endpoint / service</small></div><em>${n} errors</em></div>`).join('')||'<p class="muted">No impact detected.</p>';let peak=gs[0];let rep=`INCIDENT BRIEF\nGenerated by TraceLens (deterministic local analysis)\n\nWindow: ${start?start.toISOString():'unknown'} → ${end?end.toISOString():'unknown'}\nImpact: ${es.length} errors across ${gs.length} failure signatures${warns.length?`; ${warns.length} warnings observed`:''}.\n\nPrimary failure: ${peak?peak.sig:'No error signature detected'}\nObserved ${peak?.items.length||0} times; first seen ${peak?fmtTime(peak.items[0].time):'—'}.\n\nAffected surfaces: ${[...impacts].sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]+' ('+x[1]+')').join(', ')||'none identified'}.\n\nRecommended next step: inspect the first occurrence and correlate it with deployment, dependency, and saturation metrics. Start with the highest-frequency signature above.`;$('#reportText').textContent=rep;$('#copyBtn').onclick=()=>navigator.clipboard.writeText(rep).then(()=>{$('#copyBtn').textContent='Copied ✓';setTimeout(()=>$('#copyBtn').textContent='Copy report',1500)})}
function renderChart(es,valid){let times=es.filter(e=>!isNaN(e.time)).map(e=>e.time);let min=times[0]||new Date(),max=times.at(-1)||new Date(min.getTime()+1),span=Math.max(1,max-min),b=Array.from({length:12},()=>0);times.forEach(t=>b[Math.min(11,Math.floor((t-min)/span*12))]++);let peak=Math.max(...b,0);$('#peakLabel').textContent=peak?`peak ${peak} errors`:'no errors';$('#chart').innerHTML=b.map((n,i)=>`<div class="bar" title="${n} errors" style="height:${Math.max(4,n/Math.max(1,peak)*160)}px"><span>${i%3===0?fmtTime(new Date(+min+span*i/12)):''}</span></div>`).join('')}
function aiContext(){let es=events.filter(e=>e.level==='ERROR'||e.level==='FATAL'),warns=events.filter(e=>e.level==='WARN'),gs=groups(),valid=events.filter(e=>!isNaN(e.time)).sort((a,b)=>a.time-b.time),surfaces=new Map;es.forEach(e=>{let k=normalize(e.endpoint==='—'?e.service:e.endpoint);surfaces.set(k,(surfaces.get(k)||0)+1)});return{eventCount:events.length,errorCount:es.length,warningCount:warns.length,window:valid.length?{start:valid[0].time.toISOString(),end:valid.at(-1).time.toISOString()}:null,recurringFailures:gs.slice(0,8).map(g=>({signature:g.sig,occurrences:g.items.length,firstSeen:isNaN(g.items[0].time)?'unknown':g.items[0].time.toISOString()})),affectedSurfaces:[...surfaces].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([surface,errors])=>({surface,errors}))}}
async function requestAI(){let button=$('#aiBtn'),status=$('#aiStatus'),output=$('#aiOutput');button.disabled=true;button.textContent='Analyzing…';status.textContent='Sending redacted incident context to the hosted model…';output.hidden=true;try{let response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({incident:aiContext()})});let body=await response.json();if(!response.ok)throw new Error(body.error||'Analysis request failed.');output.textContent=body.analysis;output.hidden=false;status.textContent=`Generated by ${body.model||'the hosted model'} · raw log lines stayed in your browser.`}catch(error){let deployed=location.hostname.endsWith('github.io');status.textContent=deployed?'AI analysis needs the Vercel deployment. Deploy this repository to Vercel and add HF_TOKEN.':error.message}finally{button.disabled=false;button.textContent='Generate AI analysis'}}
function esc(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{let f=e.target.files[0];if(f)f.text().then(t=>analyze(f.name,t))};$('#demoBtn').onclick=()=>analyze('sample-incident.log',demo);$('#newFile').onclick=()=>{$('#analysis').hidden=true;window.scrollTo({top:0,behavior:'smooth'})};$('#reportBtn').onclick=()=>{$('#report').hidden=false;$('#report').scrollIntoView({behavior:'smooth'})};let dz=$('#dropzone');['dragover','dragenter'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{let f=e.dataTransfer.files[0];if(f)f.text().then(t=>analyze(f.name,t))});
